export default [
  {
    id: 1,
    title: "Dosa",
    category: "breakfast",
    price: 40,
    img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2023/06/brown-rice-dosa-recipe.jpg",
    desc: "Crispy and delicious brown rice dosas are thin crepes from South Indian Cuisine.",
  },
  {
    id: 2,
    title: "Sambar Rice",
    category: "lunch",
    price: 80,
    img: "https://www.kannammacooks.com/wp-content/uploads/sambar-sadam-made-with-brown-rice-recipe-1-3.jpg",
    desc: "Recipe for traditional sambar sadam made with brown rice in an Instant pot.",
  },
  {
    id: 3,
    title: "Rose Milk",
    category: "shakes",
    price: 40,
    img: "https://www.spiceupthecurry.com/wp-content/uploads/2023/04/rose-milk-recipe-3.jpg",
    desc: "You’ll love this easy and quick-to-make rose milk! It’s made with simple 4 ingredients and gets",
  },
  {
    id: 4,
    title: "Dal Makhani",
    category: "dinner",
    price: 140,
    img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/05/dal-makhani.jpg",
    desc: "Dal Makhani. Another popular North Indian vegetarian dish, dal makhani is a creamy preparation made with black lentils (urad dal) and served with roti.",
  },
  {
    id: 5,
    title: "idly",
    category: "breakfast",
    price: 30,
    img: "https://chakriskitchen.com/wp-content/uploads/2018/12/Idly19.jpg",
    desc: "Idly is a very popular south Indian breakfast recipe prepared with Urad dal (black gram).",
  },
  {
    id: 6,
    title: "Mutton Biryani",
    category: "lunch",
    price: 250,
    img: "https://www.cookwithnabeela.com/wp-content/uploads/2023/03/MuttonBiryani.webp",
    desc: "Mutton biryani is the epitome of Indian cuisine, with layers of beautifully spiced mutton and tender.",
  },
  {
    id: 7,
    title: "Badham Milk",
    category: "shakes",
    price: 50,
    img: "https://www.cookwithmanali.com/wp-content/uploads/2014/06/Badam-Milk.jpg",
    desc: "Popular Indian drink made with milk and almonds and flavored with saffron and cardamom! Badam Milk",
  },
  {
    id: 8,
    title: "Chana Masala",
    category: "dinner",
    price: 150,
    img: "https://www.indianveggiedelight.com/wp-content/uploads/2019/05/chana-masala-recipe-featured.jpg",
    desc: "Chana Masala or Chickpeas Curry or Chole is a vegan and gluten free, flavorful and delicious Indian dish where the chickpeas (channa) is cooked in aromatic.",
  },
  {
    id: 9,
    title: "Puri",
    category: "breakfast",
    price: 40,
    img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2020/12/poori-puri-recipe.jpg",
    desc: "Poori is an unleavened deep fried bread made with flour & salt. It is a popular breakfast food from India",
  },
  {
    id: 10,
    title: "Chicken Biryani",
    category: "lunch",
    price: 180,
    img: "https://www.licious.in/blog/wp-content/uploads/2020/12/Hyderabadi-chicken-Biryani.jpg",
    desc: "Indian royal dinners are never complete without a hot pot of aromatic and flavorful Hyderabadi Biryani.",
  },
  {
    id: 11,
    title: "Chocolate Shake",
    category: "shakes",
    price: 80,
    img: "https://tastesbetterfromscratch.com/wp-content/uploads/2021/06/Chocolate-Milkshake-5.jpg",
    desc: "This easy Chocolate Milkshake recipe is thick and creamy, made in just a few minutes.",
  },
  {
    id: 12,
    title: "Butter Chicken",
    category: "dinner",
    price: 220,
    img: "https://hips.hearstapps.com/hmg-prod/images/indian-butter-chicken2-1671199746.jpg?crop=0.778xw:0.778xh;0.105xw,0.123xh&resize=980:*",
    desc: "Murgh Makhani (Butter Chicken) India is known as the paradise of spices. The spices are essential in making the dish delicious and achieving the authentic.",
  },
];
